vim.cmd('set number')
vim.cmd('set encoding=utf-8')
vim.cmd('set tabstop=4 shiftwidth=4 expandtab')
vim.cmd('set background=dark')
vim.cmd('set conceallevel=2')
vim.cmd('set autoindent')
vim.cmd('set hlsearch')
vim.cmd('nohls')
vim.cmd('set showmode')
vim.cmd('set laststatus=2')
vim.cmd('set scrolloff=5')
vim.cmd('set rnu')
vim.cmd('set nowrapscan')
vim.cmd('set ignorecase')
vim.cmd('set smartcase')
vim.cmd('noremap <leader>1 1gt')
vim.cmd('noremap <leader>2 2gt')
vim.cmd('noremap <leader>3 3gt')
vim.cmd('noremap <leader>4 4gt')
vim.cmd('noremap <leader>5 5gt')
vim.cmd('noremap <leader>6 6gt')
vim.cmd('noremap <leader>7 7gt')
vim.cmd('noremap <leader>8 8gt')
vim.cmd('noremap <leader>9 9gt')
vim.cmd('noremap <leader>0 :tablast<cr>')

vim.keymap.set('n', '<leader>n', ':Neotree filesystem reveal left<CR>')
-- vim.keymap.set('n', '<F3>', ':Neotree filesystem reveal left<CR>')
vim.keymap.set('i', 'jk', '<esc>')

vim.keymap.set('n', '<leader>ev', ':tabnew ~/.config/nvim/lua/<cr>')
vim.keymap.set('n', '<leader>et', ':vsplit ~/.tmux.conf<cr>')
vim.keymap.set('n', '<leader>sv', ':source ~/.vimrc<cr>')
vim.keymap.set('n', '<silent> <Leader>+', ':exe "resize " . (winheight(0) * 3/2)<CR>')
vim.keymap.set('n', '<Leader>-', ':exe "resize " . (winheight(0) * 2/3)<CR>')
vim.keymap.set('n', '<Leader>>', ':exe "vertical resize " . (winwidth(0) * 3/2)<CR>')
vim.keymap.set('n', '<Leader><', ':exe "vertical resize " . (winwidth(0) * 2/3)<CR>')
vim.keymap.set('n', '<Leader>r', ':edit!<CR>')
vim.keymap.set('n', '<leader>zz', ':tab split<CR>')
vim.keymap.set('n', '<cr>', ':nohlsearch<CR>')
vim.keymap.set({'n', 'v'}, 'gj', '5j')
vim.keymap.set({'n', 'v'}, 'gk', '5k')
vim.keymap.set('n', '<leader>w', ':close<cr>')

vim.keymap.set('n', '<C-h>', '<C-w>h')
vim.keymap.set('n', '<C-j>', '<C-w>j')
vim.keymap.set('n', '<C-k>', '<C-w>k')
vim.keymap.set('n', '<C-l>', '<C-w>l')
vim.keymap.set("n", "*", ":keepjumps normal! mi*`i<CR>", { noremap = true, silent = true })

-- vim.o.foldmethod = "expr"
-- vim.o.foldexpr = "v:lua.vim.lsp.foldexpr()"
